### ISSUE TITLE
Read the previous state of the mood in the example contract

### ISSUE THREAD

**Issue by nuke-web3** [BlockDevsUnited/BasicFrontEndTutorial#4]
Want to modify or add another function like  `getMood()` in index.html to query the previous states of the mood, not just the present one. 

Possible leads:
https://docs.ethers.io/ethers.js/html/api-providers.html#contract-state

https://docs.ethers.io/ethers.js/html/api-providers.html#provider-specific-extra-api-calls

**Comment by nuke-web3** [comment]
@mpcahn - wanna help :grinning: ?

**Comment by antron3000** [comment]
Do you know how to do this offhand?
